apiVersion: apps/v1
kind: Deployment
metadata:
  name: gb-deployment
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 2
  template:
    metadata:
      name: gb-pod
      labels:
        app: guestbook
        name: gb-pod
        tier: frontend
    spec:
      containers:
        - name: gb-frontend
          image: gcr.io/google-samples/gb-frontend:v4
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: guestbook
      name: gb-pod
      tier: frontend
