apiVersion: v1
kind: Service
metadata:
  name: gb-service
  labels:
    app: guestbook
    name: gb-service
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
      app: guestbook
      name: gb-pod
      tier: frontend
