apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: guestbook
    name: redis-service
    tier: backend
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
      app: guestbook
      name: redis-pod
      tier: backend
