apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-persistent-storage
spec:
  storageClassName: slow
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /html
    server: nfs01
